import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import TechStack from "../components/TechStack";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillGoogleCircle,
  AiFillMail,
} from "react-icons/ai";
import { projects, techStacks } from "../helpers/data";
import Project from "../components/Project";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Mohammed Safvan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-8 ">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-poppins">Safvan</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-5">
            <h2 className=" text-3xl py-2 text-teal-600 font-semibold">
              Mohammed Safvan
            </h2>
            <h3 className="text-xl py-2">Full stack Developer</h3>
            <p className=" text-md leading-7 py-3 text-gray-600">
              An individual with passion for coding. Lorem ipsum, dolor sit amet
              consectetur adipisicing elit. Ex sint rem repellendus tempora
              magni ullam beatae, suscipit pariatur sed
            </p>
          </div>
          <div className=" text-4xl flex justify-center gap-5 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/mohammed-safvan-7022b21a3/"
              target="_blank"
            >
              <AiFillLinkedin className=" hover:text-teal-600 cursor-pointer" />
            </a>
            <a href="https://github.com/mohammedsafvan" target="_blank">
              <AiFillGithub className=" hover:text-teal-600 cursor-pointer" />
            </a>
            <a href="https://g.dev/mohammedsafvan" target="_blank">
              <AiFillGoogleCircle className=" hover:text-teal-600 cursor-pointer" />
            </a>
            <a href="mailto:mohammedsafvan.me@gmail.com" target="_blank">
              <AiFillMail className=" hover:text-teal-600 cursor-pointer" />
            </a>
          </div>
          <section className="py-10">
            <div>
              <h3 className=" text-2xl">Technologies I use :</h3>
              <div className="flex pt-2 pb-0.5 gap-3 flex-wrap flex-auto">
                {techStacks.map((element) => (
                  <TechStack url={element.url} imageUrl={element.imageUrl} />
                ))}
              </div>
            </div>
          </section>

          <div>
            <h3 className=" text-2xl">Projects :</h3>
            <div className="flex p-5 gap-3 flex-wrap flex-auto">
              {projects.map((element) => (
                <Project/>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
